import lunr from "C:\\Users\\User\\Git\\dokumentation-mariushau01\\node_modules\\lunr\\lunr.js";
require("C:\\Users\\User\\Git\\dokumentation-mariushau01\\node_modules\\lunr-languages\\lunr.stemmer.support.js")(lunr);
require("C:\\Users\\User\\Git\\dokumentation-mariushau01\\node_modules\\lunr-languages\\lunr.de.js")(lunr);
require("C:\\Users\\User\\Git\\dokumentation-mariushau01\\node_modules\\lunr-languages\\lunr.multi.js")(lunr);
export const language = ["de","en"];
export const removeDefaultStopWordFilter = false;
export const removeDefaultStemmer = false;
export const Mark = null;
export const searchIndexUrl = "search-index{dir}.json?_=cc3e230b";
export const searchResultLimits = 8;
export const searchResultContextMaxLength = 50;
export const explicitSearchResultPath = false;
export const searchBarShortcut = true;
export const searchBarShortcutHint = true;
export const searchBarPosition = "right";
export const docsPluginIdForPreferredVersion = undefined;
export const indexDocs = true;
export const searchContextByPaths = null;
export const hideSearchBarWithNoSearchContext = false;
export const useAllContextsWithNoSearchContext = false;